<h1><b>Statistique en Bioinformatique : </b> TME2 </h1>
<br>
L’objectif de ce TME est: 
<br>
<ul>
<li> objectif 1: comprendre les différences d'alignement global et local, </li>
<li> objectif 2: reconstruire une matrice de substitution du type Blosum, </li>
</ul>
<br>
<div class="alert alert-warning" role="alert" style="margin: 10px">
<p><b>Soumission</b></p>
<ul>
<li>Renomer le fichier TME2.ipynb pour NomEtudiant1_NomEtudiant2.ipynb </li>
<li>Soumettre sur moodle </li>
</ul>
</div>

Nom etudiant 1 : Grichi Ihsân
<br>
Nom etudiant 2 :
<br>

<b> Exercice 1 </b>: On va étudier un alignement “difficile” entre la protéine emph50s ribosomal L20 chez A. aeolicus, 
et la protéine ligase UBR5 chez l’homme (L’alignement structural est montré ci-dessous). 
<br>

<img src="bacthum.png" alt="Smiley face" height="210" width="202"> 



<br><br>
<b>A.</b> Récupérez la séquence de la protéine “E3 ubiquitin ligase UBR5” chez l’homme et de la protéine “50S ribosomal L20” chez A. aeolicus 
via le site <a href="http://www.uniprot.org/">Uniprot</a>  au format .fasta.

<br>
<b>B.</b> A l’aide du site <a href="https://www.ebi.ac.uk/Tools/psa/">psa</a>, alignez ces séquences. Commentez les faibles pourcentage d’identité malgré le bon alignement des ces structures.


Réponse : Cela est simplement dû au grand nombre de missmatch présent dans l'alignement. L'algorithme considère que l'évolution a opéré des substitutions à certaines positions plutôt que des insertions/délétions.

<b>C.</b> Récupérez la séquence de la protéine “metL Bifunctional aspartokinase/homoserine dehydrogenase 2” et de la protéine “lysC Lysine-sensitive aspartokinase 3” chez E. coli via le site <a href="http://www.uniprot.org/"> Uniprot </a> au format .fasta. Reproduisez, à l’aide du site <a href="https://www.ebi.ac.uk/Tools/psa/"> psa</a>, l’alignement global et local vu en TD. Observez la modification des résultats en changeant la matrice de substitution et/ou les pénalités de gap (“Gap_penalty” et “Extend_penalty”).

Reponse: Après avoir aligné ces deux séquences avec l'algorithme de Needlman Wunsch tout d'abord avec la matrice BLOSUM62 on constate 17.2% d'identité, 27.6% de similarité et 48.4% de gaps pour un score d'alignement final de 501.5. Lorsque l'on fait cela avec la matrice EBOLSUM30 on observe 17.4% d'identité, 30.9% de similarité et 49.1% de gaps pour un score final de 779.0. Au final même si on constate quelques légères différences dans le pourcentage de gaps et d'identité elles ne sont pas si significatives et on ne peut donc pas en déduire quelques effets de la matrice. En revanche on constate une nette différence entre les pourcentages de similairité, peut être que la matrice EBLOSUM30 est plus permissive et considère plus d'acides aminés comme possédant les mêmes propriétés physico-chimique.

<b>Exercice 2</b>: Score alignement global, local <br>
Faire une fonction pour calculer : 1) la pourcentage de identité, 2) la pourcentage de similarité, 3) le score d’un alignement en utilisant la matrix blosum62. Le calcul de la similarité doit prendre en considération les acides amine ayant la même propriété physico chimique. Dans notre cas, tous les acides amine qui ont des valeurs supérieur à zéro dans la matrice BLOSUM62. Le score basé sur la matrice blosum doit aussi prendre en considération les deux pénalités de gaps, ouverture et extension. Teste vos fonctions en utilisant le fichier test.fasta


In [12]:
import numpy as np

#variable initiation
aa = ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V', 'X']

#parameters
q = 21
gap_open = -5
gap_ext = 0.5

#files
input_test_f = 'test.fasta'
input_blosum_f = 'BLOSUM62.txt'

#For a simple test use:
input_test_f = 'testToy.fasta'



In [13]:
#Read the test.fasta file
def read_fasta (input_f):
    """
    Input1 input_f: fasta file name
    Output1 arr_seqs: List of sequences 
    REMARK : We keep only the sequences, identifiers are not necessary
    """
    arr_seqs = []
    seq =''
    
    flux = open(input_f)
    for line in flux :
        line = line.rstrip()
        
        
        if line[0] == '>' :
            if seq!= '':
                arr_seqs.append(seq)
            seq = ''

        else:
            seq+=line[:]
            
    arr_seqs.append(seq)
    
    
    return arr_seqs


testAln = read_fasta(input_test_f)
print (testAln)
#It shlould print ['ACCD', 'A-CD'] when using toy

['ACCD', 'A-CD']


In [14]:
#read Blosum
def read_blosum (input_f):
    """
    Input1 input_f : blosum file name
    Output1: a matrix of dimention [q-1, q-1] 
    REMARK : You should eliminate the last four columns and last four rows of Blosum file
    """
    M = []
    
    flux = open(input_f)
    for line in flux:
        line = line.rstrip()
        if line[0] != '#' and line[0] != ' ':
            line = line.split(None, 24)
            M.append(line[1:])
    
    M = np.array(M)
    blosum = np.zeros((len(M) - 4, len(M[0]) - 4 ) )
    
    
    for i in range(len(blosum)):
        for j in range(len(blosum[0])):
            blosum[i, j] = int(M[i, j])
    
    
    return blosum

matr_62 = read_blosum (input_blosum_f)
print(matr_62)

[[ 4. -1. -2. -2.  0. -1. -1.  0. -2. -1. -1. -1. -1. -2. -1.  1.  0. -3.
  -2.  0.]
 [-1.  5.  0. -2. -3.  1.  0. -2.  0. -3. -2.  2. -1. -3. -2. -1. -1. -3.
  -2. -3.]
 [-2.  0.  6.  1. -3.  0.  0.  0.  1. -3. -3.  0. -2. -3. -2.  1.  0. -4.
  -2. -3.]
 [-2. -2.  1.  6. -3.  0.  2. -1. -1. -3. -4. -1. -3. -3. -1.  0. -1. -4.
  -3. -3.]
 [ 0. -3. -3. -3.  9. -3. -4. -3. -3. -1. -1. -3. -1. -2. -3. -1. -1. -2.
  -2. -1.]
 [-1.  1.  0.  0. -3.  5.  2. -2.  0. -3. -2.  1.  0. -3. -1.  0. -1. -2.
  -1. -2.]
 [-1.  0.  0.  2. -4.  2.  5. -2.  0. -3. -3.  1. -2. -3. -1.  0. -1. -3.
  -2. -2.]
 [ 0. -2.  0. -1. -3. -2. -2.  6. -2. -4. -4. -2. -3. -3. -2.  0. -2. -2.
  -3. -3.]
 [-2.  0.  1. -1. -3.  0.  0. -2.  8. -3. -3. -1. -2. -1. -2. -1. -2. -2.
   2. -3.]
 [-1. -3. -3. -3. -1. -3. -3. -4. -3.  4.  2. -3.  1.  0. -3. -2. -1. -3.
  -1.  3.]
 [-1. -2. -3. -4. -1. -2. -3. -4. -3.  2.  4. -2.  2.  0. -3. -2. -1. -2.
  -1.  1.]
 [-1.  2.  0. -1. -3.  1.  1. -2. -1. -3. -2.  5. -1. -3. -1.  0.

In [15]:
def indentite_calcul(seq1, seq2, gap_open, gap_ext, matr_62):
    """
    Input1 seq1 : sequence
    Input2 seq2 : sequence
    Input3 gap_open : gap open penality
    Input4 gap_ext : gap extention penality
    Input5 matr_62 :  a matrix of dimention [q-1, q-1] representing substitution matrix
    Output1 ident: sequence identity
    Output2 similaire: sequence similarity
    Output3 score: aligment score
    """
    
    score = 0
    similaire = 0
    ident=0
    n = len(seq1)
    gap1 = False
    gap2 = False
    
    for k in range(n):
        nt1 = seq1[k]
        nt2 = seq2[k]
        if nt1 == '-':
            gap2 = False
            if not gap1:
                score += gap_open
                gap1 = True
            else:
                score+=gap_ext
                
        elif nt2 == '-':
            gap1 = False
            if not gap2:
                score+= gap_open
                gap2 = True
            else:
                score+=gap_ext
                
        elif nt1!= '-' and nt2!= '-':
            index1 = aa.index(nt1)
            index2 = aa.index(nt2)
            if nt1 == nt2 :
                ident += 1/n
                similaire += 1/n
                score += matr_62[index1, index2]
            else:
                if matr_62[index1, index2] > 0 :
                    similaire += 1/n
                score += matr_62[index1, index2]
    return ident, similaire, score

print(testAln)
identitee,similarity,score = indentite_calcul(testAln[0], testAln[1], gap_open, gap_ext, matr_62)
print ("identitee= ", identitee , " similarity= ", similarity, " score= ", score )

#identitee=  0.75  similarity=  0.75  score=  14.0

['ACCD', 'A-CD']
identitee=  0.75  similarity=  0.75  score=  14.0


<b>Exercice 3</b>: Matrice de substitution <br>
Faire une programme (plusieurs fonctions seront nécessaires) pour produire une matrix de substitution comme Blosum. Utiliser l’alignement du fichiers <b>blocks.dat</b> Vous pouvez tester vous fonctions sue le fichier <b>blockToy.dat</b>. 


In [16]:
from itertools import combinations, combinations_with_replacement
from collections import Counter

input_block_f = 'blockToy.dat'


#For a simple test do:
q = 3
aa = ['A', 'B', 'C']



In [6]:
#read alignment file
from io import StringIO 
import sys

def readAlnFile(input_f):
    """
    Input1 input_f : Alignment File name
    Output1 aln : List of aligned sequences
    Output2 cols : Number of colums (L)
    """
    aln = []
    flux = open(input_f)
    
    for line in flux:
        line= line.lstrip().rstrip()
        aln.append(line)
        
    cols = len(aln[0])
    
    return aln, cols

aln, cols  = readAlnFile(input_block_f)
#cols = 43
cols = 5 #testing toy
print ( aln)


['ABCCB', 'ACABA', 'CBCCB', 'ACBBB']


In [7]:
#compute fij frequences
def frequencies (aln, cols, aa):
    """
    Input1 aln : List of aligned sequences
    Input2 cols : Number of colums in the aligment (L)
    Input3 aa: residue alphabet
    Output1  pairs_freq_dict: a dictionary containing residue pair frequencies
    """
    #generate all aa combination
    pairs_freq_dict = {x:0 for x in combinations_with_replacement(aa,2)}
    aa.sort()
    n = len(aln[0])
    paire = []
    K = 0
    
    for k in range(n):
        for i in range(cols):
            for j in range(i+1, cols-1):
                paire.append([aln[i][k], aln[j][k]])
                paire[K].sort()
                pairs_freq_dict[(paire[K][0], paire[K][1])]+=1
                K+=1
                
                
    return pairs_freq_dict

pairs_freq_dict = frequencies (aln, cols, aa)
print (pairs_freq_dict)
#{('A', 'A'): 3, ('A', 'B'): 4, ('A', 'C'): 5, ('B', 'B'): 5, ('B', 'C'): 10, ('C', 'C'): 3}

{('A', 'A'): 3, ('A', 'B'): 4, ('A', 'C'): 5, ('B', 'B'): 5, ('B', 'C'): 10, ('C', 'C'): 3}


In [8]:
#compute T
def calcule_T(pairs_freq_dict):
    """
    Input1 pairs_freq_dict: a dictionary containing residue pair frequencies
    Output1 : T, the overall sum 
    """
    T = 0
    for v in pairs_freq_dict.values():
        T+=v
    
    return T

T = calcule_T(pairs_freq_dict)
print (T)
#30

30


In [9]:
#compute pi
def calcule_p_is(pairs_freq_dict, T):
    """
    Compute the probability of each residue.
    Input1 pairs_freq_dict: a dictionary containing residue pair frequencies
    Input2 T : the overall sum 
    Output1 pi: List of probabilities
    REMARK : You can compute qij directly from pairs_freq_dict or create a function to do so.
    """
    L = []
    for key in pairs_freq_dict.keys():
        L.append(key[0])
        L.append(key[1])
        
    L = set(L)
    L = [k for k in L]
    L.sort()
    pi = [0 for k in range(len(L))]
    
    for nt in L:
        for key in pairs_freq_dict.keys():
            for nt2 in key:
                if nt2 == nt:
                    pi[L.index(nt)] += pairs_freq_dict[key]/2/T
    
    return pi


pi = calcule_p_is(pairs_freq_dict, T)
print (pi)
#[0.25, 0.4, 0.35]

[0.25, 0.4, 0.35]


In [10]:
#compute Sij
def calcule_S_i_j(pairs_freq_dict, p, T):
    """
    Input1 pairs_freq_dict: a dictionary containing residue pair frequencies
    Input2 p: List of probabilities for each residue
    Input3 T: the overall sum 
    Output1 s: Score for each residue pair
    """
    n = len(aa)
    s = np.zeros((n, n))
    for key in pairs_freq_dict:
        i = aa.index(key[1])
        j = aa.index(key[0])
        qij = pairs_freq_dict[key]/T
        pi = p[i]
        pj = p[j]
        
        #condition quand pi =0 ou pj = 0 ce qui est le cas quand on test sur block.dat
        if pi == 0:
            pi = 0.0000001
        if pj == 0:
            pj = 0.0000001
            
            
        if p[i] == p[j]:
            sij = np.log(qij/(pi*pj))
        else:
            sij = np.log(qij/(2*(pi*pj)))
        s[i, j] = sij
        s[j, i] = sij
        
    return s

Sij = calcule_S_i_j(pairs_freq_dict, pi, T)
print (Sij)
#[[0.47000362924573563, -0.40546510810816444, -0.048790164169431945], [-0.40546510810816444, 0.04082199452025478, 0.17435338714477774], [-0.048790164169431945, 0.17435338714477774, -0.20294084399669016]]

[[ 0.47000363 -0.40546511 -0.04879016]
 [-0.40546511  0.04082199  0.17435339]
 [-0.04879016  0.17435339 -0.20294084]]


In [11]:
#print Matrix
Sij_c = [["{:0.2f}".format(x) for x in l] for l in Sij]
print('Blosum matrix from Blocks database:')
row_format ="{:>5}|" * (len(aa) + 1)
print(row_format.format("", *aa))
for aa, row in zip(aa, Sij_c):
	print(row_format.format(aa, *row))

Blosum matrix from Blocks database:
     |    A|    B|    C|
    A| 0.47|-0.41|-0.05|
    B|-0.41| 0.04| 0.17|
    C|-0.05| 0.17|-0.20|
