# TP UPGMA/NJ 

In [1]:
import numpy as np

In [25]:
def readMatrix(nameFile, n): #n = nombre d'espèces dans la matrice
    Matrix={}
    M = []
    i = True
    
    flux = open(nameFile)
    for line in flux:
        line = line.rstrip().lstrip()
        if line[0] != '#':
            line = line.split(None, n)
            if i:
                alphabet = line
            else :
                M.append(line[1:])
        i = False
            
    M = np.array(M, dtype = int)
    
    return M, alphabet

MD, alphabet = readMatrix('matrice.txt', 7)
print(MD, '\n\n', alphabet)

[[ 0 19 27  8 33 18 13]
 [19  0 31 18 36  1 13]
 [27 31  0 26 41 32 29]
 [ 8 18 26  0 31 17 14]
 [33 36 41 31  0 35 28]
 [18  1 32 17 35  0 12]
 [13 13 29 14 28 12  0]] 

 ['a', 'b', 'c', 'd', 'e', 'f', 'g']


In [26]:
def diag(MD):
    n = len(MD)
    for i in range(n):
        for j in range(i, n):
            if i==j :
                MD[i, j] = 1000
    pass

diag(MD)
print(MD)

[[1000   19   27    8   33   18   13]
 [  19 1000   31   18   36    1   13]
 [  27   31 1000   26   41   32   29]
 [   8   18   26 1000   31   17   14]
 [  33   36   41   31 1000   35   28]
 [  18    1   32   17   35 1000   12]
 [  13   13   29   14   28   12 1000]]


In [33]:
def distance(i, j, MD, leni, lenj):
    for k in range(len(MD)):
        if i!=k and j!=k:
            MD[i, k] =  ( MD[i, k]*leni + MD[k, j]*lenj ) / (leni + lenj)
            MD[k, i] = MD[i, k]
    pass

In [40]:
MD, alphabet = readMatrix('matrice.txt', 7)
diag(MD)

def UPGMA(MD, alphabet):
    D = {}
    n = len(MD)
    k = 0
    newick = ''
    
    while k < n - 1:
        i, j = np.unravel_index(np.argmin(MD, axis = None), MD.shape)
        
        cluster = alphabet[i] + alphabet[j]
        d = MD[i, j] / 2
        
        D[alphabet[i]] = d
        D[alphabet[j]] = d
        
        distance(i, j, MD, len(alphabet[i]), len(alphabet[j]))
        
        alphabet[i] = '(' + alphabet[i] + ', ' + alphabet[j] + ')'  #fait newick automatiquement
            
        del alphabet[j]

        MD = np.delete(MD, j, axis = 0)
        MD = np.delete(MD, j, axis = 1)
        k+=1
    
    return D, alphabet[0]


Arbre, newick = UPGMA(MD, alphabet)
print(Arbre, '\n\n', newick, '\n')
print(Newick('(b : 0.5, f : 0.5)', 'g'))

{'b': 0.5, 'f': 0.5, 'a': 4.0, 'd': 4.0, '(b, f)': 6.0, 'g': 6.0, '(a, d)': 8.0, '((b, f), g)': 8.0, '((a, d), ((b, f), g))': 14.0, 'c': 14.0, '(((a, d), ((b, f), g)), c)': 16.5, 'e': 16.5} 

 ((((a, d), ((b, f), g)), c), e) 

((b : 0.5, f : 0.5), g)
